routes/web.php
<?php

/*

 Route::group(['middleware' => ['role:super-admin|writer']], function () {

});

Route::group(['middleware' => ['permission:publish articles|edit articles']], function () {

});

*/


Auth::routes( [ 'verify' => true ] );


//<editor-fold desc="Guest Routes">
Route::group( [ 'middleware' => [ 'guest' ] ], function () {

	Route::get( '/', function () {
		return view( 'welcome' );
	} );

	Route::resource( 'service-request', 'ServiceRequestController' );

} );
//</editor-fold>

// All Authenticate user routes
Route::group( [ 'middleware' => [ 'auth' ] ], function () {
	//<editor-fold desc="Redirecting user after login base on role">
	Route::get( '/home', 'HomeController@index' )->name( 'home' );  // this controller handel the rediraction after login
	//</editor-fold>

	Route::get( 'set/status/online', 'UserOnlineController' );  // this controller handel the rediraction after login
	Route::get( 'set/status/offline', 'UserOfflineController' );  // this controller handel the rediraction after login

	//<editor-fold desc="Admin Route">
	Route::group( [
		'prefix'     => 'admin',
		'middleware' => [ 'role:admin' ],
		'namespace'  => 'Admin',
		'as'         => 'admin.'
	], function () {
		// All Admin Routes +++++
		Route::get( '/', 'DashboardController@home' )->name( 'home' );
		Route::resource( 'service', 'ServiceController' );
		Route::resource( 'service-category', 'ServiceCategoryController' );
		Route::resource( 'car-brand', 'CarBrandController' );
		Route::resource( 'car-type', 'CarTypeController' );
	} );
	//</editor-fold>


	//<editor-fold desc="Service Partner Route">

	Route::group( [
		'prefix'     => 'service-partner',
		'middleware' => [ 'role:service_partner' ],
		'namespace'  => 'ServicePartner',
		'as'         => 'service.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );
		Route::post( 'offer/accepted', 'ServiceOfferController@accepted' )->name( 'offer.accepted' );
		Route::post( 'offer/declined', 'ServiceOfferController@decliced' )->name( 'offer.declined' );
	} );
	//</editor-fold>

	//<editor-fold desc="Inventory Partner Route">
	Route::group( [
		'prefix'     => 'inventory-partner',
		'middleware' => [ 'role:inventory_partner' ],
		'namespace'  => 'InventoryPartner',
		'as'         => 'inventory.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="towing Partner Route">
	Route::group( [
		'prefix'     => 'towing-partner',
		'middleware' => [ 'role:towing_partner' ],
		'namespace'  => 'TowingPartner',
		'as'         => 'towing.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Collusion Partner Route">
	Route::group( [
		'prefix'     => 'collusion-center-partner',
		'middleware' => [ 'role:collusion_center_partner' ],
		'namespace'  => 'CollusionPartner',
		'as'         => 'collusion.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Banking Partner Route">
	Route::group( [
		'prefix'     => 'banking-partner',
		'middleware' => [ 'role:banking_partner' ],
		'namespace'  => 'BankingPartner',
		'as'         => 'banking.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Insurance Partner Route">
	Route::group( [
		'prefix'     => 'insurance-partner',
		'middleware' => [ 'role:insurance_partner' ],
		'namespace'  => 'InsurancePartner',
		'as'         => 'insurance.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Insurance Partner Route">
	Route::group( [
		'prefix'     => 'insurance-partner',
		'middleware' => [ 'role:insurance_partner' ],
		'namespace'  => 'InsurancePartner',
		'as'         => 'insurance.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Customer Route">
	Route::group( [
		'prefix'     => 'customer',
		'middleware' => [ 'role:customer' ],
		'namespace'  => 'Customer',
		'as'         => 'customer.'
	], function () {
		//All Customer Routes +++++
		Route::get( '/dashboard', 'DashboardController@home' )->name( 'home' );
		Route::post( '/charge', 'PaymentController@charge' )->name( 'charge' );
		Route::resource( 'service-request', 'ServiceRequestController' );

	} );
	//</editor-fold>

} );

use App\Events\ServiceRequestDeclined;

Route::get( '/dashboarasdcascasdmailk', function () {
	Mail::raw( 'Text', function ( $message ) {
		$message->to( 'miraj.net.xp@gmail.com' );
	} );

} );


Route::get( '/dashboarasdcascasd/{id}', function ( $id ) {
	$user = \App\User::find( $id );
//	$cards = $user->cards();


	$response = $user->charge( 100 );
	dd( $response );


} );

app/Models/Service.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Service extends Model {

	protected $fillable = [ 'name', 'slang', 'service_category_id' ];

	public function serviceRequests() {
		return $this->morphedByMany( 'App\Models\ServiceRequest', 'serviceable' );
	}

	public function category() {
		return $this->belongsTo('App\Models\ServiceCategory','service_category_id');
	}
}

app/Http/Controllers/Admin/ServiceController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Service;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Permission;

class ServiceController extends Controller {

	public function __construct() {

	}

	public function index() {
		return view( 'admin.Service.index' );
	}

	public function store( Request $request ) {
		//TODO validation imp
		$request->validate( [
			'slang' => 'required|unique:permissions,name',
		] );

		Service::create( $request->all() );
		if ( $request->service_category_id ) {
			Permission::create( [
				'name'         => $request->slang,
				'display_name' => $request->name,
				'type'         => 'service'
			] );
		} else {
			Permission::create( [
				'name'         => $request->slang,
				'display_name' => $request->name,
				'type'         => 'extra_service'
			] );
		}

		return redirect()->back();
	}
}

resources/views/admin/Service/index-service-category.blade.php
@extends('layouts.app')

@section('content')
    <div class="az-content-header d-block d-md-flex">
        <div>
            <h2 class="az-content-title tx-24 mg-b-5 mg-b-lg-8">Service Categories</h2>
        </div>
    </div><!-- az-content-header -->
    <div class="az-content-body">
        <div class="row row-sm mg-b-15 mg-sm-b-20">
            <div class="col-lg-6 col-xl-6">
                <div class="card card-dashboard-six">
                    <h2 class="az-content-title tx-24 mg-b-5 mg-b-lg-8">Add A Service Category</h2>
                    <hr>
                    <form action="{{route('admin.service-category.store')}}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label>Category Name</label>
                            <input type="text" name="name" class="form-control"
                                   placeholder="Enter Service eg. Service Technicians and Mechanics">
                        </div><!-- form-group -->
                        <div class="form-group">
                            <label>Category slang (Should be Unique across the platform )</label>
                            <input type="text" autocomplete="off" name="slang" class="form-control"
                                   placeholder="Enter slang eg st&e ">
                        </div><!-- form-group -->
                        <button class="btn btn-az-primary btn-block">Add</button>
                    </form>
                </div><!-- card -->
            </div><!-- col -->
            <div class="col-lg-6 col-xl-6 mg-t-20 mg-lg-t-0">
                <div class="bd pd-20">
                    <ul class="list-unstyled">
                        @if(count($serviceCategories)==0)
                            <div class="card bd-0">
                                <h2 class="text-center">No service category added yet!</h2>
                            </div>
                        @else
                            @foreach($serviceCategories as $serviceCategorie)
                                <div class="card bd-0">
                                    <h5 class="mg-b-10 tx-inverse">{{$serviceCategorie->name}}</h5>
                                    <p>{{$serviceCategorie->slang}}</p>
                                </div>
                                <br>
                            @endforeach
                        @endif
                    </ul>
                </div>
            </div><!-- col -->
        </div><!-- row -->
    </div><!-- az-content-body -->
@endsection

resources/views/admin/Service/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="az-content-header d-block d-md-flex">
        <div>
            <h2 class="az-content-title tx-24 mg-b-5 mg-b-lg-8">Service</h2>
        </div>
    </div><!-- az-content-header -->
    <div class="az-content-body">
        <div class="row row-sm mg-b-15 mg-sm-b-20">
            <div class="col-lg-6 col-xl-6">
                <div class="card card-dashboard-six">
                    <h2 class="az-content-title tx-24 mg-b-5 mg-b-lg-8">Add Service</h2>
                    <hr>
                    <form action="{{route('admin.service.store')}}" method="POST">
                        @csrf
                        <div class="form-group">
                            <label>Service Name</label>
                            <input type="text" name="name" class="form-control"
                                   placeholder="Enter Service eg. Tire Replacement Service">
                        </div><!-- form-group -->
                        <div class="form-group">
                            <label>Service slang (Should be Unique across the platform )</label>
                            <input type="text" autocomplete="off" name="slang" class="form-control"
                                   placeholder="Enter slang eg tire_replacement_ervice">

                            @if ($errors->has('slang'))
                                <span class="text-danger">
                                        <strong>{{ $errors->first('slang') }}</strong>
                                </span>
                            @endif
                        </div><!-- form-group -->
                        <div class="form-group">
                            <label>Select Category (If this is an extra service, leave it blank.) </label>
                            <select name="service_category_id" class="form-control">
                                @if(count($serviceCategories)==0)
                                    <option>Add a category first</option>
                                @else
                                    <option value>Select a category</option>
                                    @foreach($serviceCategories as $serviceCategorie)
                                        <option value="{{$serviceCategorie->id}}">{{$serviceCategorie->name}}</option>
                                    @endforeach
                                @endif
                            </select>
                        </div><!-- form-group -->
                        <button class="btn btn-az-primary btn-block">Add</button>
                    </form>
                </div><!-- card -->
            </div><!-- col -->
            <div class="col-lg-6 col-xl-6 mg-t-20 mg-lg-t-0">
                <div class="bd pd-20">
                    <ul class="list-unstyled">
                        @if(count($services)==0)
                            <div class="card bd-0">
                                <h2 class="text-center">No service added yet!</h2>
                            </div>
                        @else
                            @foreach($services as $service)
                                <div class="card bd-0">
                                    <h5 class="mg-b-10 tx-inverse">{{$service->name}}</h5>
                                    <p>{{$service->slang}}</p>
                                    <p>Category : {{($service->category)?$service->category->name:'Extra Service'}}</p>
                                </div>
                                <br>
                            @endforeach
                        @endif
                    </ul>
                </div>
            </div><!-- col -->
        </div><!-- row -->
    </div><!-- az-content-body -->
@endsection