routes/web.php
<?php

/*

 Route::group(['middleware' => ['role:super-admin|writer']], function () {

});

Route::group(['middleware' => ['permission:publish articles|edit articles']], function () {

});

*/


Auth::routes( [ 'verify' => true ] );


//<editor-fold desc="Guest Routes">
Route::group( [ 'middleware' => [ 'guest' ] ], function () {

	Route::get( '/', function () {
		return view( 'welcome' );
	} );

	Route::resource( 'service-request', 'ServiceRequestController' );

} );
//</editor-fold>

// All Authenticate user routes
Route::group( [ 'middleware' => [ 'auth' ] ], function () {
	//<editor-fold desc="Redirecting user after login base on role">
	Route::get( '/home', 'HomeController@index' )->name( 'home' );  // this controller handel the rediraction after login
	//</editor-fold>

	Route::get( 'set/status/online', 'UserOnlineController' );  // this controller handel the rediraction after login
	Route::get( 'set/status/offline', 'UserOfflineController' );  // this controller handel the rediraction after login

	//<editor-fold desc="Admin Route">
	Route::group( [
		'prefix'     => 'admin',
		'middleware' => [ 'role:admin' ],
		'namespace'  => 'Admin',
		'as'         => 'admin.'
	], function () {
		// All Admin Routes +++++
		Route::get( '/', 'DashboardController@home' )->name( 'home' );
		Route::resource( 'service', 'ServiceController' );
		Route::resource( 'service-category', 'ServiceCategoryController' );
		Route::resource( 'car-brand', 'CarBrandController' );
		Route::resource( 'car-type', 'CarTypeController' );
	} );
	//</editor-fold>


	//<editor-fold desc="Service Partner Route">

	Route::group( [
		'prefix'     => 'service-partner',
		'middleware' => [ 'role:service_partner' ],
		'namespace'  => 'ServicePartner',
		'as'         => 'service.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );
		Route::post( 'offer/accepted', 'ServiceOfferController@accepted' )->name( 'offer.accepted' );
		Route::post( 'offer/declined', 'ServiceOfferController@decliced' )->name( 'offer.declined' );
	} );
	//</editor-fold>

	//<editor-fold desc="Inventory Partner Route">
	Route::group( [
		'prefix'     => 'inventory-partner',
		'middleware' => [ 'role:inventory_partner' ],
		'namespace'  => 'InventoryPartner',
		'as'         => 'inventory.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="towing Partner Route">
	Route::group( [
		'prefix'     => 'towing-partner',
		'middleware' => [ 'role:towing_partner' ],
		'namespace'  => 'TowingPartner',
		'as'         => 'towing.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Collusion Partner Route">
	Route::group( [
		'prefix'     => 'collusion-center-partner',
		'middleware' => [ 'role:collusion_center_partner' ],
		'namespace'  => 'CollusionPartner',
		'as'         => 'collusion.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Banking Partner Route">
	Route::group( [
		'prefix'     => 'banking-partner',
		'middleware' => [ 'role:banking_partner' ],
		'namespace'  => 'BankingPartner',
		'as'         => 'banking.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Insurance Partner Route">
	Route::group( [
		'prefix'     => 'insurance-partner',
		'middleware' => [ 'role:insurance_partner' ],
		'namespace'  => 'InsurancePartner',
		'as'         => 'insurance.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Insurance Partner Route">
	Route::group( [
		'prefix'     => 'insurance-partner',
		'middleware' => [ 'role:insurance_partner' ],
		'namespace'  => 'InsurancePartner',
		'as'         => 'insurance.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Customer Route">
	Route::group( [
		'prefix'     => 'customer',
		'middleware' => [ 'role:customer' ],
		'namespace'  => 'Customer',
		'as'         => 'customer.'
	], function () {
		//All Customer Routes +++++
		Route::get( '/dashboard', 'DashboardController@home' )->name( 'home' );
		Route::post( '/charge', 'PaymentController@charge' )->name( 'charge' );
		Route::resource( 'service-request', 'ServiceRequestController' );

	} );
	//</editor-fold>

} );

use App\Events\ServiceRequestDeclined;

Route::get( '/dashboarasdcascasdmailk', function () {
	Mail::raw( 'Text', function ( $message ) {
		$message->to( 'miraj.net.xp@gmail.com' );
	} );

} );


Route::get( '/dashboarasdcascasd/{id}', function ( $id ) {
	$user = \App\User::find( $id );
//	$cards = $user->cards();


	$response = $user->charge( 100 );
	dd( $response );


} );

app/Models/CarBrand.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class CarBrand extends Model implements HasMedia {
	use HasMediaTrait;

	protected $fillable=['name','desc','avatar'];

}

app/Http/Controllers/Admin/CarBrandController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\CarBrand;
use Illuminate\Http\Request;

class CarBrandController extends Controller {
	private $CarBrand;

	public function __construct() {
		$this->CarBrand = (CarBrand::all())->sortBy( 'name' );

	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public $asd = 'ascasc';

	public function index() {
		return view( 'admin.CarBrand.index', [ 'carBrands' => $this->CarBrand ] );
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function create() {

		return view( 'admin.CarBrand.index', [ 'carBrands' => $this->CarBrand ] );
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function store( Request $request ) {

		$carBrand = CarBrand::create( $request->only( [ 'name', 'desc', 'avatar' ] ) );

		return redirect()->back();
	}


	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  \App\Models\CarBrand $carBrand
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function edit( CarBrand $carBrand ) {
		return view( 'admin.CarBrand.edit', [ 'carBrands' => $this->CarBrand, 'car' => $carBrand ] );
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  \Illuminate\Http\Request $request
	 * @param  \App\Models\CarBrand $carBrand
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function update( Request $request, CarBrand $carBrand ) {
		$carBrand = $carBrand->update( $request->only( [ 'name', 'desc', 'avatar' ] ) );

		return redirect()->back();
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  \App\Models\CarBrand $carBrand
	 *
	 * @return \Illuminate\Http\Response
	 */
	public function destroy( CarBrand $carBrand ) {
		//
	}
}

resources/views/admin/CarBrand/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="az-content-header d-block d-md-flex">
        <div>
            <h2 class="az-content-title tx-24 mg-b-5 mg-b-lg-8">Car Brand</h2>
        </div>
    </div><!-- az-content-header -->
    <div class="az-content-body">
        <div class="row row-sm mg-b-15 mg-sm-b-20">
            <div class="col-lg-6 col-xl-6">
                <div class="card card-dashboard-six">
                    <h2 class="az-content-title tx-24 mg-b-5 mg-b-lg-8">Add Brand</h2>
                    <hr>
                    <form action="{{route('admin.car-brand.update',['car_brand'=>$car->id])}}" method="POST">
                        @csrf

                        @method('PUT')
                        <div class="form-group">
                            <label>Brand Name</label>
                            <input type="text" name="name" value="{{$car->name}}" class="form-control"
                                   placeholder="Enter Brand Name">
                        </div><!-- form-group -->
                        <div class="form-group">
                            <label>Description (optional)</label>
                            <input type="text" autocomplete="off" value="{{$car->desc}}" name="desc"
                                   class="form-control"
                                   placeholder="Enter Description">
                        </div><!-- form-group -->
                        <div class="form-group">
                            <label>Avatar (optional)</label>
                            <input type="text" autocomplete="off" value="{{$car->avatar}}" name="avatar"
                                   class="form-control"
                                   placeholder="Enter Description">
                        </div><!-- form-group -->
                        <button class="btn btn-az-warning btn-warning btn-block">Update</button>
                    </form>
                </div><!-- card -->
            </div><!-- col -->
            <div class="col-lg-6 col-xl-6 mg-t-20 mg-lg-t-0">
                <div class="bd pd-20">
                    <ul class="list-unstyled">
                        @foreach($carBrands as $carBrand)
                            <div class="card bd-0">
                                <li class="media d-block d-sm-flex border pa-5">
                                    <img src="{{$carBrand->avatar}}"
                                         class="wd-100p wd-sm-100 rounded mg-sm-r-20 mg-b-20 mg-sm-b-0 " alt="">
                                    <div class="media-body">
                                        <h5 class="mg-b-10 tx-inverse">{{$carBrand->name}}</h5>
                                        {{$carBrand->desc}}
                                        <p class="text-right">
                                            <button class="btn-warning btn">Edit</button>
                                        </p>
                                    </div>
                                </li>
                            </div>
                            <br>
                        @endforeach
                    </ul>
                </div>
            </div><!-- col -->
        </div><!-- row -->
    </div><!-- az-content-body -->
@endsection

resources/views/admin/CarBrand/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="az-content-header d-block d-md-flex">
        <div>
            <h2 class="az-content-title tx-24 mg-b-5 mg-b-lg-8">Car Brand</h2>
        </div>
    </div><!-- az-content-header -->
    <div class="az-content-body">
        <div class="row row-sm mg-b-15 mg-sm-b-20">
            <div class="col-lg-6 col-xl-6">
                <div class="card card-dashboard-six">
                    <h2 class="az-content-title tx-24 mg-b-5 mg-b-lg-8">Add Brand</h2>
                    <hr>
                    <form action="{{route('admin.car-brand.store')}}" method="POST" >
                        @csrf
                        <div class="form-group">
                            <label>Brand Name</label>
                            <input type="text" name="name" class="form-control" placeholder="Enter Brand Name">
                        </div><!-- form-group -->
                        <div class="form-group">
                            <label>Description (Optional)</label>
                            <input type="text" autocomplete="off" name="desc" class="form-control"
                                   placeholder="Enter Description">
                        </div><!-- form-group -->
                        <div class="form-group">
                            <label>Avatar (Optional)</label>
                            <input type="text" autocomplete="off" name="avatar" class="form-control"
                                   placeholder="Enter Description">
                        </div><!-- form-group -->
                        <button class="btn btn-az-primary btn-block">Add</button>
                    </form>
                </div><!-- card -->
            </div><!-- col -->
            <div class="col-lg-6 col-xl-6 mg-t-20 mg-lg-t-0">
                <div class="bd pd-20">
                    <ul class="list-unstyled">
                        @foreach($carBrands as $carBrand)
                            <div class="card bd-0">
                                <li class="media d-block d-sm-flex border pa-5">
                                    <img src="{{$carBrand->avatar}}"
                                         class="wd-100p wd-sm-100 rounded mg-sm-r-20 mg-b-20 mg-sm-b-0 " alt="">
                                    <div class="media-body">
                                        <h5 class="mg-b-10 tx-inverse">{{$carBrand->name}}</h5>
                                        {{$carBrand->desc}}
                                        <p class="text-right pd-r-10">
                                            <a class="btn-warning btn"
                                               href="{{route('admin.car-brand.edit',['car_brand'=>$carBrand->id])}}">Edit</a>
                                        </p>
                                    </div>
                                </li>
                            </div>
                            <br>
                        @endforeach
                    </ul>
                </div>
            </div><!-- col -->
        </div><!-- row -->
    </div><!-- az-content-body -->
@endsection