routes/web.php
<?php

/*

 Route::group(['middleware' => ['role:super-admin|writer']], function () {

});

Route::group(['middleware' => ['permission:publish articles|edit articles']], function () {

});

*/


Auth::routes( [ 'verify' => true ] );


//<editor-fold desc="Guest Routes">
Route::group( [ 'middleware' => [ 'guest' ] ], function () {

	Route::get( '/', function () {
		return view( 'welcome' );
	} );

	Route::resource( 'service-request', 'ServiceRequestController' );

} );
//</editor-fold>

// All Authenticate user routes
Route::group( [ 'middleware' => [ 'auth' ] ], function () {
	//<editor-fold desc="Redirecting user after login base on role">
	Route::get( '/home', 'HomeController@index' )->name( 'home' );  // this controller handel the rediraction after login
	//</editor-fold>

	Route::get( 'set/status/online', 'UserOnlineController' );  // this controller handel the rediraction after login
	Route::get( 'set/status/offline', 'UserOfflineController' );  // this controller handel the rediraction after login

	//<editor-fold desc="Admin Route">
	Route::group( [
		'prefix'     => 'admin',
		'middleware' => [ 'role:admin' ],
		'namespace'  => 'Admin',
		'as'         => 'admin.'
	], function () {
		// All Admin Routes +++++
		Route::get( '/', 'DashboardController@home' )->name( 'home' );
		Route::resource( 'service', 'ServiceController' );
		Route::resource( 'service-category', 'ServiceCategoryController' );
		Route::resource( 'car-brand', 'CarBrandController' );
		Route::resource( 'car-type', 'CarTypeController' );
	} );
	//</editor-fold>


	//<editor-fold desc="Service Partner Route">

	Route::group( [
		'prefix'     => 'service-partner',
		'middleware' => [ 'role:service_partner' ],
		'namespace'  => 'ServicePartner',
		'as'         => 'service.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );
		Route::post( 'offer/accepted', 'ServiceOfferController@accepted' )->name( 'offer.accepted' );
		Route::post( 'offer/declined', 'ServiceOfferController@decliced' )->name( 'offer.declined' );
	} );
	//</editor-fold>

	//<editor-fold desc="Inventory Partner Route">
	Route::group( [
		'prefix'     => 'inventory-partner',
		'middleware' => [ 'role:inventory_partner' ],
		'namespace'  => 'InventoryPartner',
		'as'         => 'inventory.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="towing Partner Route">
	Route::group( [
		'prefix'     => 'towing-partner',
		'middleware' => [ 'role:towing_partner' ],
		'namespace'  => 'TowingPartner',
		'as'         => 'towing.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Collusion Partner Route">
	Route::group( [
		'prefix'     => 'collusion-center-partner',
		'middleware' => [ 'role:collusion_center_partner' ],
		'namespace'  => 'CollusionPartner',
		'as'         => 'collusion.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Banking Partner Route">
	Route::group( [
		'prefix'     => 'banking-partner',
		'middleware' => [ 'role:banking_partner' ],
		'namespace'  => 'BankingPartner',
		'as'         => 'banking.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Insurance Partner Route">
	Route::group( [
		'prefix'     => 'insurance-partner',
		'middleware' => [ 'role:insurance_partner' ],
		'namespace'  => 'InsurancePartner',
		'as'         => 'insurance.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Insurance Partner Route">
	Route::group( [
		'prefix'     => 'insurance-partner',
		'middleware' => [ 'role:insurance_partner' ],
		'namespace'  => 'InsurancePartner',
		'as'         => 'insurance.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Customer Route">
	Route::group( [
		'prefix'     => 'customer',
		'middleware' => [ 'role:customer' ],
		'namespace'  => 'Customer',
		'as'         => 'customer.'
	], function () {
		//All Customer Routes +++++
		Route::get( '/dashboard', 'DashboardController@home' )->name( 'home' );
		Route::post( '/charge', 'PaymentController@charge' )->name( 'charge' );
		Route::resource( 'service-request', 'ServiceRequestController' );

	} );
	//</editor-fold>

} );

use App\Events\ServiceRequestDeclined;

Route::get( '/dashboarasdcascasdmailk', function () {
	Mail::raw( 'Text', function ( $message ) {
		$message->to( 'miraj.net.xp@gmail.com' );
	} );

} );


Route::get( '/dashboarasdcascasd/{id}', function ( $id ) {
	$user = \App\User::find( $id );
//	$cards = $user->cards();


	$response = $user->charge( 100 );
	dd( $response );


} );

resources/views/includes/card-details.blade.php
<div class="modal fade" id="card-details" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Modal title</h4>
            </div>
            <div class="modal-body">

                <form action="/charge" method="post" id="payment-form">
                    <div class="form-row">
                        <label for="card-element">
                            Credit or debit card
                        </label>
                        <div id="card-element">
                            <!-- A Stripe Element will be inserted here. -->
                        </div>

                        <!-- Used to display form errors. -->
                        <div id="card-errors" role="alert"></div>
                    </div>

                    <button>Submit Payment</button>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

resources/views/includes/footer.blade.php
    <div class="container-fluid pd-t-0-f ht-100p">
        <span>&copy; 2019 Availby | All Right Reserved</span>
        <span>Designed by: Webmaster</span>
    </div><!-- container -->

resources/views/includes/header.blade.php
<div class="container-fluid">
    <div class="az-header-left">
        <a href="" id="azSidebarToggle" class="az-header-menu-icon"><span></span></a>
    </div><!-- az-header-left -->
    <div class="az-header-center">
        <input type="search" class="form-control" placeholder="Search for anything...">
        <button class="btn"><i class="fas fa-search"></i></button>
    </div><!-- az-header-center -->
    <div class="az-header-right">
        @if(auth()->user()->hasRole('customer'))
            <div class="az-header-message pd-15">
                <button data-toggle="modal" data-target="#serviceBookingModel"
                        class="btn btn-outline-indigo btn-rounded btn-block">Book Now
                </button>
            </div><!-- az-header-message -->
        @endif
        <div class="az-header-message">
            <a href="app-chat.html"><i class="typcn typcn-messages"></i></a>
        </div><!-- az-header-message -->

        <div class="dropdown az-header-notification">
            <a href="" class="new"><i class="typcn typcn-bell"></i></a>
            <div class="dropdown-menu">
                <div class="az-dropdown-header mg-b-20 d-sm-none">
                    <a href="" class="az-header-arrow"><i class="icon ion-md-arrow-back"></i></a>
                </div>
                <h6 class="az-notification-title">Notifications</h6>
                <p class="az-notification-text">You have 2 unread notification</p>
                <div class="az-notification-list">
                    <div class="media new">
                        <div class="az-img-user"><img src="https://via.placeholder.com/500" alt=""></div>
                        <div class="media-body">
                            <p>Congratulate <strong>Socrates Itumay</strong> for work anniversaries</p>
                            <span>Mar 15 12:32pm</span>
                        </div><!-- media-body -->
                    </div><!-- media -->
                    <div class="media new">
                        <div class="az-img-user online"><img src="https://via.placeholder.com/500" alt=""></div>
                        <div class="media-body">
                            <p><strong>Joyce Chua</strong> just created a new blog post</p>
                            <span>Mar 13 04:16am</span>
                        </div><!-- media-body -->
                    </div><!-- media -->
                    <div class="media">
                        <div class="az-img-user"><img src="https://via.placeholder.com/500" alt=""></div>
                        <div class="media-body">
                            <p><strong>Althea Cabardo</strong> just created a new blog post</p>
                            <span>Mar 13 02:56am</span>
                        </div><!-- media-body -->
                    </div><!-- media -->
                    <div class="media">
                        <div class="az-img-user"><img src="https://via.placeholder.com/500" alt=""></div>
                        <div class="media-body">
                            <p><strong>Adrian Monino</strong> added new comment on your photo</p>
                            <span>Mar 12 10:40pm</span>
                        </div><!-- media-body -->
                    </div><!-- media -->
                </div><!-- az-notification-list -->
                <div class="dropdown-footer"><a href="">View All Notifications</a></div>
            </div><!-- dropdown-menu -->
        </div><!-- az-header-notification -->
        <div class="dropdown az-profile-menu">
            <a href="" class="az-img-user"><img src="https://via.placeholder.com/500" alt=""></a>
            <div class="dropdown-menu">
                <div class="az-dropdown-header d-sm-none">
                    <a href="" class="az-header-arrow"><i class="icon ion-md-arrow-back"></i></a>
                </div>
                <div class="az-header-profile">
                    <div class="az-img-user">
                        <img src="https://via.placeholder.com/500" alt="">
                    </div><!-- az-img-user -->
                    <h6>Aziana Pechon</h6>
                    <span>
                             @foreach(\Spatie\Permission\Models\Permission::all() as $per)
                            @can($per->name)
                                {{$per->display_name}}
                            @endcan
                        @endforeach
                        </span>
                </div><!-- az-header-profile -->

                <a href="" class="dropdown-item"><i class="typcn typcn-user-outline"></i> My Profile</a>
                <a href="" class="dropdown-item"><i class="typcn typcn-edit"></i> Edit Profile</a>
                <a href="" class="dropdown-item"><i class="typcn typcn-time"></i> Activity Logs</a>
                <a href="" class="dropdown-item"><i class="typcn typcn-cog-outline"></i> Account Settings</a>
                <a href="#" onclick="document.getElementById('logout-form').submit();" class="dropdown-item"><i
                            class="typcn typcn-power-outline"></i>
                    <form id="logout-form" action="{{route('logout')}}" method="POST"> @csrf</form>
                    <span form="logout-form">Sign
                        Out
                    </span>
                </a>
            </div><!-- dropdown-menu -->
        </div>
    </div><!-- az-header-right -->
</div><!-- container -->

resources/views/includes/sidebar.blade.php
<div class="az-sidebar-header">
    <a href="index.html" class="az-logo">az<span>i</span>a</a>
</div><!-- az-sidebar-header -->
<div class="az-sidebar-loggedin">
    <div class="az-img-user online"><img src="https://via.placeholder.com/500" alt=""></div>
    <div class="media-body">
        <h6>{{auth()->user()->first_name}}</h6>
        <span>
            @foreach(\Spatie\Permission\Models\Permission::all() as $per)
                @can($per->name)
                    {{$per->name}}
                @endcan
            @endforeach
        </span>
    </div><!-- media-body -->
</div><!-- az-sidebar-loggedin -->
<div class="az-sidebar-body">
    <ul class="nav">
        <li class="nav-label">Main Menu</li>
        <li class="nav-item">
            <a  data-toggle="modal" data-target="#serviceBookingModel" class="nav-link with-sub"><i class="typcn typcn-clipboard"></i>Accounts Overview</a>
            <ul class="nav-sub">
                <li class="nav-sub-item"><a href="service_ptnr_db.html" class="nav-sub-link">Service Partners</a></li>
                <li class="nav-sub-item"><a href="inventory_ptnr_db.html" class="nav-sub-link">Inventory Partner</a>
                </li>
                <li class="nav-sub-item"><a href="towing_ptnr_db.html" class="nav-sub-link">Towing Partners</a></li>
                <li class="nav-sub-item"><a href="collusion_ptnr_db.html" class="nav-sub-link">Collusion Center
                        Partners</a></li>
                <li class="nav-sub-item"><a href="banking_ptnr_db.html" class="nav-sub-link">Banking Partners</a></li>
                <li class="nav-sub-item"><a href="insurance_ptnr_db.html" class="nav-sub-link">Insurance Partners</a>
                </li>
            </ul>
        </li>
        <!-- nav-item -->
        <li class="nav-item">
            <a href="" class="nav-link with-sub"><i class="typcn typcn-chart-bar-outline"></i>Payments</a>
            <ul class="nav-sub">
                <li class="nav-sub-item"><a href="service_overview.html" class="nav-sub-link">Overview</a></li>
                <li class="nav-sub-item"><a href="chart-flot.html" class="nav-sub-link">Qucik Pay</a></li>
                <li class="nav-sub-item"><a href="chart-chartjs.html" class="nav-sub-link">Payment History</a></li>
                <li class="nav-sub-item"><a href="chart-peity.html" class="nav-sub-link">Quick Pay FAQ</a></li>
            </ul>
        </li><!-- nav-item -->
        @if(auth()->user()->hasRole('admin'))
            <li class="nav-item">
                <a href="" class="nav-link with-sub"><i class="icon ion-ios-locate"></i>Service Management</a>
                <ul class="nav-sub">
                    <li class="nav-sub-item"><a href="{{route('admin.service-category.index')}}" class="nav-sub-link">Service
                            Category</a></li>
                    <li class="nav-sub-item"><a href="{{route('admin.service.index')}}" class="nav-sub-link">Service</a>
                    </li>
                </ul>
            </li><!-- nav-item -->
        @endif
        <li class="nav-item">
            <a href="" class="nav-link with-sub"><i class="typcn typcn-map"></i>Refferals</a>
            <ul class="nav-sub">
                <li class="nav-sub-item"><a href="refferals_db.html" class="nav-sub-link">Overview</a></li>
            </ul>
        </li><!-- nav-item -->
        <li class="nav-item">
            <a href="" class="nav-link with-sub"><i class="typcn typcn-tabs-outline"></i>Rewards</a>
            <ul class="nav-sub">
                <li class="nav-sub-item"><a href="rewards_db.html" class="nav-sub-link">Overview</a></li>
            </ul>
        </li><!-- nav-item -->
        <li class="nav-item">
            <a href="" class="nav-link with-sub"><i class="typcn typcn-tabs-outline"></i>Support</a>
            <ul class="nav-sub">
                <li class="nav-sub-item"><a href="table-basic.html" class="nav-sub-link">Overview</a></li>
            </ul>
        </li><!-- nav-item -->
        <li class="nav-item">
            <a href="" class="nav-link with-sub"><i class="typcn typcn-archive"></i>Settings</a>
            <ul class="nav-sub">
                <li class="nav-sub-item"><a href="util-background.html" class="nav-sub-link">Overview</a></li>
                <li class="nav-sub-item"><a href="util-border.html" class="nav-sub-link">Profile</a></li>
                <li class="nav-sub-item"><a href="util-display.html" class="nav-sub-link">Banking</a></li>
                <li class="nav-sub-item"><a href="util-flex.html" class="nav-sub-link">Documents</a></li>
                <li class="nav-sub-item"><a href="util-height.html" class="nav-sub-link">Service Profile</a></li>
            </ul>
        </li><!-- nav-item -->
    </ul><!-- nav -->
</div><!-- az-sidebar-body -->