routes/web.php
<?php

/*

 Route::group(['middleware' => ['role:super-admin|writer']], function () {

});

Route::group(['middleware' => ['permission:publish articles|edit articles']], function () {

});

*/


Auth::routes( [ 'verify' => true ] );


//<editor-fold desc="Guest Routes">
Route::group( [ 'middleware' => [ 'guest' ] ], function () {

	Route::get( '/', function () {
		return view( 'welcome' );
	} );

	Route::resource( 'service-request', 'ServiceRequestController' );

} );
//</editor-fold>

// All Authenticate user routes
Route::group( [ 'middleware' => [ 'auth' ] ], function () {
	//<editor-fold desc="Redirecting user after login base on role">
	Route::get( '/home', 'HomeController@index' )->name( 'home' );  // this controller handel the rediraction after login
	//</editor-fold>

	Route::get( 'set/status/online', 'UserOnlineController' );  // this controller handel the rediraction after login
	Route::get( 'set/status/offline', 'UserOfflineController' );  // this controller handel the rediraction after login

	//<editor-fold desc="Admin Route">
	Route::group( [
		'prefix'     => 'admin',
		'middleware' => [ 'role:admin' ],
		'namespace'  => 'Admin',
		'as'         => 'admin.'
	], function () {
		// All Admin Routes +++++
		Route::get( '/', 'DashboardController@home' )->name( 'home' );
		Route::resource( 'service', 'ServiceController' );
		Route::resource( 'service-category', 'ServiceCategoryController' );
		Route::resource( 'car-brand', 'CarBrandController' );
		Route::resource( 'car-type', 'CarTypeController' );
	} );
	//</editor-fold>


	//<editor-fold desc="Service Partner Route">

	Route::group( [
		'prefix'     => 'service-partner',
		'middleware' => [ 'role:service_partner' ],
		'namespace'  => 'ServicePartner',
		'as'         => 'service.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );
		Route::post( 'offer/accepted', 'ServiceOfferController@accepted' )->name( 'offer.accepted' );
		Route::post( 'offer/declined', 'ServiceOfferController@decliced' )->name( 'offer.declined' );
	} );
	//</editor-fold>

	//<editor-fold desc="Inventory Partner Route">
	Route::group( [
		'prefix'     => 'inventory-partner',
		'middleware' => [ 'role:inventory_partner' ],
		'namespace'  => 'InventoryPartner',
		'as'         => 'inventory.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="towing Partner Route">
	Route::group( [
		'prefix'     => 'towing-partner',
		'middleware' => [ 'role:towing_partner' ],
		'namespace'  => 'TowingPartner',
		'as'         => 'towing.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Collusion Partner Route">
	Route::group( [
		'prefix'     => 'collusion-center-partner',
		'middleware' => [ 'role:collusion_center_partner' ],
		'namespace'  => 'CollusionPartner',
		'as'         => 'collusion.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Banking Partner Route">
	Route::group( [
		'prefix'     => 'banking-partner',
		'middleware' => [ 'role:banking_partner' ],
		'namespace'  => 'BankingPartner',
		'as'         => 'banking.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Insurance Partner Route">
	Route::group( [
		'prefix'     => 'insurance-partner',
		'middleware' => [ 'role:insurance_partner' ],
		'namespace'  => 'InsurancePartner',
		'as'         => 'insurance.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Insurance Partner Route">
	Route::group( [
		'prefix'     => 'insurance-partner',
		'middleware' => [ 'role:insurance_partner' ],
		'namespace'  => 'InsurancePartner',
		'as'         => 'insurance.partner.'
	], function () {
		//All User Routes +++++
		Route::get( 'dashboard', 'DashboardController@home' )->name( 'home' );

	} );
	//</editor-fold>

	//<editor-fold desc="Customer Route">
	Route::group( [
		'prefix'     => 'customer',
		'middleware' => [ 'role:customer' ],
		'namespace'  => 'Customer',
		'as'         => 'customer.'
	], function () {
		//All Customer Routes +++++
		Route::get( '/dashboard', 'DashboardController@home' )->name( 'home' );
		Route::post( '/charge', 'PaymentController@charge' )->name( 'charge' );
		Route::resource( 'service-request', 'ServiceRequestController' );

	} );
	//</editor-fold>

} );

use App\Events\ServiceRequestDeclined;

Route::get( '/dashboarasdcascasdmailk', function () {
	Mail::raw( 'Text', function ( $message ) {
		$message->to( 'miraj.net.xp@gmail.com' );
	} );

} );


Route::get( '/dashboarasdcascasd/{id}', function ( $id ) {
	$user = \App\User::find( $id );
//	$cards = $user->cards();


	$response = $user->charge( 100 );
	dd( $response );


} );

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Global site tag (gtag.js')}}) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-130582519-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }

        gtag('js', new Date());

        gtag('config', 'UA-130582519-1');
    </script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="user-uid" content="{{ auth()->user()->uid }}">
    <meta name="user-id" content="{{ auth()->user()->id }}">
    <meta name="user-roles" content="{{ json_encode( ( auth()->user()->roles )->pluck( 'name' ) )}}">
    <!-- Twitter -->
    <meta name="twitter:site" content="@themepixels">
    <meta name="twitter:creator" content="@themepixels">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Azia">
    <meta name="twitter:description" content="Responsive Bootstrap 4 Dashboard Template">
    <meta name="twitter:image" content="http://themepixels.me/azia/img/azia-social.png">

    <!-- Facebook -->
    <meta property="og:url" content="http://themepixels.me/azia">
    <meta property="og:title" content="Azia">
    <meta property="og:description" content="Responsive Bootstrap 4 Dashboard Template">

    <meta property="og:image" content="http://themepixels.me/azia/img/azia-social.png">
    <meta property="og:image:secure_url" content="http://themepixels.me/azia/img/azia-social.png">
    <meta property="og:image:type" content="image/png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="600">

    <!-- Meta -->
    <meta name="description" content="Responsive Bootstrap 4 Dashboard Template">
    <meta name="author" content="ThemePixels">

    <title>{{config('app.name')}} | Dashboard</title>

    <!-- vendor css -->
    <link href="{{asset('dashboard/lib/fontawesome-free/css/all.min.css')}}" rel="stylesheet">
    <link href="{{asset('dashboard/lib/ionicons/css/ionicons.min.css')}}" rel="stylesheet">
    <link href="{{asset('dashboard/lib/typicons.font/typicons.css')}}" rel="stylesheet">
    <link href="{{asset('dashboard/lib/flag-icon-css/css/flag-icon.min.css')}}" rel="stylesheet">
    <link href="{{asset('dashboard/lib/jqvmap/jqvmap.min.css')}}" rel="stylesheet">

    <!-- azia CSS -->
    <link rel="stylesheet" href="{{asset('dashboard/css/azia.css')}}">
    <link href="{{asset('css/app.css')}}" rel="stylesheet">
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCdSks7O6JWUkj2C0lIAM_vQt6mYj51PSo&libraries=places"></script>
    <script src="https://js.stripe.com/v3/"></script>



</head>
<body class="az-body az-body-sidebar">
<div class="az-sidebar">
    @include('includes.sidebar')
</div><!-- az-sidebar -->

<div id="app" class="az-content az-content-dashboard-two">
    <customer-partner-service-offer-model></customer-partner-service-offer-model>
    <service-partner-service-offer-model></service-partner-service-offer-model>
    <div class="az-header">
        @include('includes.header')
    </div><!-- az-header -->
    @yield('content')
    <div class="az-footer ht-40">
        @include('includes.footer')
    </div><!-- az-footer -->
</div><!-- az-content -->


<script src="{{asset('js/app.js')}}"></script>
{{--<form action="{{route('customer.charge')}}" method="POST">--}}
{{--@csrf--}}
{{--<script--}}
{{--src="https://checkout.stripe.com/checkout.js" class="stripe-button"--}}
{{--data-key="pk_test_5pk6M97gItjqB5IGsaqW6ef2"--}}
{{--data-amount="1999"--}}
{{--data-name="Stripe Demo"--}}
{{--data-description="Online course about integrating Stripe"--}}
{{--data-image="https://stripe.com/img/documentation/checkout/marketplace.png"--}}
{{--data-locale="auto"--}}
{{--data-currency="usd">--}}
{{--</script>--}}
{{--</form>--}}

<script src="{{asset('dashboard/lib/jquery/jquery.min.js')}}"></script>
<script src="{{asset('dashboard/lib/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{asset('dashboard/lib/ionicons/ionicons.js')}}"></script>
<script src="{{asset('dashboard/lib/jquery-sparkline/jquery.sparkline.min.js')}}"></script>
<script src="{{asset('dashboard/lib/raphael/raphael.min.js')}}"></script>
<script src="{{asset('dashboard/lib/jqvmap/jquery.vmap.min.js')}}"></script>
<script src="{{asset('dashboard/lib/jqvmap/maps/jquery.vmap.usa.js')}}"></script>

<script src="{{asset('dashboard/js/azia.js')}}"></script>
<script>
    $(function () {
        'use strict'

        $('.az-sidebar .with-sub').on('click', function (e) {
            e.preventDefault();
            $(this).parent().toggleClass('show');
            $(this).parent().siblings().removeClass('show');
        })

        $(document).on('click touchstart', function (e) {
            e.stopPropagation();

            // closing of sidebar menu when clicking outside of it
            if (!$(e.target).closest('.az-header-menu-icon').length) {
                var sidebarTarg = $(e.target).closest('.az-sidebar').length;
                if (!sidebarTarg) {
                    $('body').removeClass('az-sidebar-show');
                }
            }
        });


        $('#azSidebarToggle').on('click', function (e) {
            e.preventDefault();

            if (window.matchMedia('(min-width: 992px)').matches) {
                $('body').toggleClass('az-sidebar-hide');
            } else {
                $('body').toggleClass('az-sidebar-show');
            }
        })


    });
</script>
</body>
</html>